review/urls.py
from django.urls import path
from . import views

app_name = 'review'

urlpatterns = [
  path('', views.index, name='index'),
  path('create_review/', views.create_review, name='create_review'),
  path('create_team/', views.create_team, name='create_team'),
]

uniform/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('review/', include('review.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

review/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Team(models.Model):
  nationality = models.CharField(max_length = 100)
  team_name = models.CharField(max_length = 60)
  logo = models.ImageField(blank=True, upload_to='image/logo/')

class Uniform(models.Model):
  # on_delete=models.CASCADE 은 만약 위에 Team 모델이 지워지면, 그에 해당하는 모든 uniform의 정보들이 지워지는 것이다
  # on_delete=models.SET_NULL, Team 모델에서, 하나의 팀이 지워지면, 그에 연관된 모든 uniform의 team 정보들은 NULL 값으로 변경된다
  team_pk = models.ForeignKey(Team, null=True, on_delete=models.SET_NULL, db_column='team_pk')
  season = models.CharField(max_length = 60)
  price = models.IntegerField()
  rating = models.IntegerField()
  content = models.TextField(validators=[MinValueValidator(0), MaxValueValidator(5)])
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  picture = models.ImageField(blank=True, upload_to='image/uniform')

review/forms.py
from django import forms
from .models import Team, Uniform

class TeamForm(forms.ModelForm):
  class Meta:
    model = Team
    fields = '__all__'

class UniformForm(forms.ModelForm):
  class Meta:
    model = Uniform
    fields = fields = '__all__'
    exclude = ('team_pk',)

review/views.py
from django.shortcuts import render, redirect
from .models import Team, Uniform
from .forms import TeamForm, UniformForm

# Create your views here.
def index(request):
  return render(request, 'review/index.html')

def create_review(request):

  teams = Team.objects.all().order_by('team_name')

  if request.method == "POST":
    uniform_form = UniformForm(request.POST)
    if uniform_form.is_valid():
      uniform_form.save()
      return redirect('review:index')
  else:
    uniform_form = UniformForm()

  context = {
    'uniform_form': uniform_form,
    'teams': teams,
  }

  return render(request, 'review/create_review.html', context)

def create_team(request):
  if request.method == "POST":
    team_form = TeamForm(request.POST)
    if team_form.is_valid():
      team_form.save()
      return redirect('review:create_review')
  else:
    team_form = TeamForm()

  context = {
    'team_form': team_form,
  }
  return render(request, 'review/create_team.html', context)

review/templates/review/create_review.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block title %}Create Uniform Review{% endblock title %}
{% block css %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock css %}

{% block content %}
  <div class="container my-5">
    <h1 >유니폼 리뷰 작성하기</h1>
    <select class="form-select mt-4 mb-2" aria-label="Default select example">
      <option selected>Choose club</option>
      {% for team in teams%}
        <option value="{{ team.pk }}">{{ team.team_name }}</option>
      {% endfor %}
    </select>
    <a class="btn btn-primary mb-2 btn-sm" href="{% url 'review:create_team' %}" role="button">새로운 팀 추가하기</a>
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form uniform_form %}
      <input class="btn btn-primary" type="submit" value="Submit">
    </form>
  </div>

{% endblock content %}

review/templates/review/create_team.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block title %}Create Team{% endblock title %}
{% block css %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock css %}

{% block content %}
  <div class="container my-5">
    <h1>팀 추가하기</h1>
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form team_form %}
      <input class="btn btn-primary" type="submit" value="Submit">
    </form>
  </div>

{% endblock content %}

review/templates/review/index.html
{% extends 'base.html' %}
{% block title %}Uniform{% endblock title %}
{% block css %}{% endblock css %}

{% block content %}
<h1>index.html</h1>

{% endblock content %}